[package]
description = "USB Interface definitions for CrabUSB"
edition.workspace = true
license.workspace = true
name = "usb-if"
repository.workspace = true
version = "0.4.0"

[dependencies]
anyhow = { version = "1", default-features = false}
futures = {workspace = true, features = ["alloc"]}
log = {workspace = true}
num_enum = {version = "0.7", default-features = false}
spin = "0.10"
thiserror = {workspace = true}
